language: c

before_install:
  - sudo apt update
  - sudo apt install cmake

before_script:
  - pip3 install --user cpplint

compiler: clang

script:
  - cpplint main.c
  - cppcheck main.c
  - valgrind --leak-check=full --show-leak-kinds=all main.c
  - gcc -g -Wall -Wextra main.c -o main
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "cppcheck"
      - "valgrind"
    update: true