language: c

before_install:
  - sudo apt update
  - sudo apt install cmake

before_script:
  - pip3 install --user cpplint

compiler:
  - gcc
  - clang

script:
  - cpplint main.c
  - cppcheck main.c
  - gcc -std=c11 -Wall -Wpedantic -c -fPIC libdynamic.c
  - gcc -shared -o libdynamic.so libdynamic.o
  - gcc -std=c11 -Wall -Wpedantic --coverage -c *.c
  - gcc -o zadanie_2_multithread_proga *.o -fprofile-arcs -ftest-coverage -g -L. -ldynamic -lstatic -Wl,-rpath,.
  - ./tp_hw_2
  - gcov *.c
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "cppcheck"
    update: true
